
namespace Botwave.XQP.API.Proxies
{

    //------------------------------------------------------------------------------
    // <auto-generated>
    //     此代码由工具生成。
    //     运行时版本:2.0.50727.4927
    //
    //     对此文件的更改可能会导致不正确的行为，并且如果
    //     重新生成代码，这些更改将会丢失。
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    // 
    // 此源代码由 wsdl 自动生成, Version=2.0.50727.3038。
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "InterfaceManagerSoap", Namespace = "http://tempuri.org/")]
    public partial class InterfaceManager : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback ValiateInterfaceOperationCompleted;

        /// <remarks/>
        public InterfaceManager(string url)
        {
            this.Url = url;// "http://iams.gz.gmcc.net/ws/InterfaceManager.asmx";
        }

        /// <remarks/>
        public event ValiateInterfaceCompletedEventHandler ValiateInterfaceCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValiateInterface", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ValidateInfaceResult ValiateInterface(string systemid, string sysAccount, string sysPassword, string interfaceId, string transferSystemId, string transferSysAccount, string transferSysPassword)
        {
            object[] results = this.Invoke("ValiateInterface", new object[] {
                    systemid,
                    sysAccount,
                    sysPassword,
                    interfaceId,
                    transferSystemId,
                    transferSysAccount,
                    transferSysPassword});
            return ((ValidateInfaceResult)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginValiateInterface(string systemid, string sysAccount, string sysPassword, string interfaceId, string transferSystemId, string transferSysAccount, string transferSysPassword, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ValiateInterface", new object[] {
                    systemid,
                    sysAccount,
                    sysPassword,
                    interfaceId,
                    transferSystemId,
                    transferSysAccount,
                    transferSysPassword}, callback, asyncState);
        }

        /// <remarks/>
        public ValidateInfaceResult EndValiateInterface(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ValidateInfaceResult)(results[0]));
        }

        /// <remarks/>
        public void ValiateInterfaceAsync(string systemid, string sysAccount, string sysPassword, string interfaceId, string transferSystemId, string transferSysAccount, string transferSysPassword)
        {
            this.ValiateInterfaceAsync(systemid, sysAccount, sysPassword, interfaceId, transferSystemId, transferSysAccount, transferSysPassword, null);
        }

        /// <remarks/>
        public void ValiateInterfaceAsync(string systemid, string sysAccount, string sysPassword, string interfaceId, string transferSystemId, string transferSysAccount, string transferSysPassword, object userState)
        {
            if ((this.ValiateInterfaceOperationCompleted == null))
            {
                this.ValiateInterfaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValiateInterfaceOperationCompleted);
            }
            this.InvokeAsync("ValiateInterface", new object[] {
                    systemid,
                    sysAccount,
                    sysPassword,
                    interfaceId,
                    transferSystemId,
                    transferSysAccount,
                    transferSysPassword}, this.ValiateInterfaceOperationCompleted, userState);
        }

        private void OnValiateInterfaceOperationCompleted(object arg)
        {
            if ((this.ValiateInterfaceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValiateInterfaceCompleted(this, new ValiateInterfaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tempuri.org/")]
    public partial class ValidateInfaceResult
    {

        private int appAuthField;

        private bool returnValueField;

        private string returnMessageField;

        /// <remarks/>
        public int AppAuth
        {
            get
            {
                return this.appAuthField;
            }
            set
            {
                this.appAuthField = value;
            }
        }

        /// <remarks/>
        public bool ReturnValue
        {
            get
            {
                return this.returnValueField;
            }
            set
            {
                this.returnValueField = value;
            }
        }

        /// <remarks/>
        public string ReturnMessage
        {
            get
            {
                return this.returnMessageField;
            }
            set
            {
                this.returnMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void ValiateInterfaceCompletedEventHandler(object sender, ValiateInterfaceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValiateInterfaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ValiateInterfaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ValidateInfaceResult Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ValidateInfaceResult)(this.results[0]));
            }
        }
    }
}