//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1434
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.1432。
// 

namespace Test
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WorkflowDesignerServiceSoap", Namespace = "http://www.botwave.com/")]
    public partial class WorkflowDesignerService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback SaveWorkflowXmlOperationCompleted;

        /// <remarks/>
        public WorkflowDesignerService()
        {
            this.Url = "http://localhost:4206/Web/apps/xqp2/pages/workflows/designer/DesignerService.asmx" +
                "";
        }

        /// <remarks/>
        public event SaveWorkflowXmlCompletedEventHandler SaveWorkflowXmlCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.botwave.com/SaveWorkflowXml", RequestNamespace = "http://www.botwave.com/", ResponseNamespace = "http://www.botwave.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SaveWorkflowXml(string key, string xmlData)
        {
            object[] results = this.Invoke("SaveWorkflowXml", new object[] {
                    key,
                    xmlData});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSaveWorkflowXml(string key, string xmlData, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SaveWorkflowXml", new object[] {
                    key,
                    xmlData}, callback, asyncState);
        }

        /// <remarks/>
        public string EndSaveWorkflowXml(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void SaveWorkflowXmlAsync(string key, string xmlData)
        {
            this.SaveWorkflowXmlAsync(key, xmlData, null);
        }

        /// <remarks/>
        public void SaveWorkflowXmlAsync(string key, string xmlData, object userState)
        {
            if ((this.SaveWorkflowXmlOperationCompleted == null))
            {
                this.SaveWorkflowXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveWorkflowXmlOperationCompleted);
            }
            this.InvokeAsync("SaveWorkflowXml", new object[] {
                    key,
                    xmlData}, this.SaveWorkflowXmlOperationCompleted, userState);
        }

        private void OnSaveWorkflowXmlOperationCompleted(object arg)
        {
            if ((this.SaveWorkflowXmlCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveWorkflowXmlCompleted(this, new SaveWorkflowXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void SaveWorkflowXmlCompletedEventHandler(object sender, SaveWorkflowXmlCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveWorkflowXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SaveWorkflowXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
