//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1434
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=2.0.50727.1432。
// 
namespace Test
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "GratuityFlowServiceSoap", Namespace = "http://www.botwave.com/")]
    public partial class GratuityFlowService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback SendGratuityFlowOperationCompleted;

        private System.Threading.SendOrPostCallback ApplyListDsOperationCompleted;

        private System.Threading.SendOrPostCallback ApplyRowDsOperationCompleted;

        /// <remarks/>
        public GratuityFlowService()
        {
            //this.Url = "http://localhost:4206/Web/apps/czmcc/ws/GratuityFlowService.asmx";
            this.Url = "http://ef.cz.gmcc.net/apps/czmcc/ws/GratuityFlowService.asmx";
        }

        public GratuityFlowService(string url)
        {
            this.Url = url;
        }

        /// <remarks/>
        public event SendGratuityFlowCompletedEventHandler SendGratuityFlowCompleted;

        /// <remarks/>
        public event ApplyListDsCompletedEventHandler ApplyListDsCompleted;

        /// <remarks/>
        public event ApplyRowDsCompletedEventHandler ApplyRowDsCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.botwave.com/SendGratuityFlow", RequestNamespace = "http://www.botwave.com/", ResponseNamespace = "http://www.botwave.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendGratuityFlow(string title, string fromEmployeeId, string fromEmployeeName, string toEmployeeId, string fileUrl, string detailUrl, int applyStyle, string description)
        {
            object[] results = this.Invoke("SendGratuityFlow", new object[] {
                    title,
                    fromEmployeeId,
                    fromEmployeeName,
                    toEmployeeId,
                    fileUrl,
                    detailUrl,
                    applyStyle,
                    description});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSendGratuityFlow(string title, string fromEmployeeId, string fromEmployeeName, string toEmployeeId, string fileUrl, string detailUrl, int applyStyle, string description, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SendGratuityFlow", new object[] {
                    title,
                    fromEmployeeId,
                    fromEmployeeName,
                    toEmployeeId,
                    fileUrl,
                    detailUrl,
                    applyStyle,
                    description}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndSendGratuityFlow(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void SendGratuityFlowAsync(string title, string fromEmployeeId, string fromEmployeeName, string toEmployeeId, string fileUrl, string detailUrl, int applyStyle, string description)
        {
            this.SendGratuityFlowAsync(title, fromEmployeeId, fromEmployeeName, toEmployeeId, fileUrl, detailUrl, applyStyle, description, null);
        }

        /// <remarks/>
        public void SendGratuityFlowAsync(string title, string fromEmployeeId, string fromEmployeeName, string toEmployeeId, string fileUrl, string detailUrl, int applyStyle, string description, object userState)
        {
            if ((this.SendGratuityFlowOperationCompleted == null))
            {
                this.SendGratuityFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendGratuityFlowOperationCompleted);
            }
            this.InvokeAsync("SendGratuityFlow", new object[] {
                    title,
                    fromEmployeeId,
                    fromEmployeeName,
                    toEmployeeId,
                    fileUrl,
                    detailUrl,
                    applyStyle,
                    description}, this.SendGratuityFlowOperationCompleted, userState);
        }

        private void OnSendGratuityFlowOperationCompleted(object arg)
        {
            if ((this.SendGratuityFlowCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendGratuityFlowCompleted(this, new SendGratuityFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.botwave.com/ApplyListDs", RequestNamespace = "http://www.botwave.com/", ResponseNamespace = "http://www.botwave.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ApplyListDs(string employeeId)
        {
            object[] results = this.Invoke("ApplyListDs", new object[] {
                    employeeId});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginApplyListDs(string employeeId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ApplyListDs", new object[] {
                    employeeId}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndApplyListDs(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void ApplyListDsAsync(string employeeId)
        {
            this.ApplyListDsAsync(employeeId, null);
        }

        /// <remarks/>
        public void ApplyListDsAsync(string employeeId, object userState)
        {
            if ((this.ApplyListDsOperationCompleted == null))
            {
                this.ApplyListDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApplyListDsOperationCompleted);
            }
            this.InvokeAsync("ApplyListDs", new object[] {
                    employeeId}, this.ApplyListDsOperationCompleted, userState);
        }

        private void OnApplyListDsOperationCompleted(object arg)
        {
            if ((this.ApplyListDsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApplyListDsCompleted(this, new ApplyListDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.botwave.com/ApplyRowDs", RequestNamespace = "http://www.botwave.com/", ResponseNamespace = "http://www.botwave.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ApplyRowDs(string applyId)
        {
            object[] results = this.Invoke("ApplyRowDs", new object[] {
                    applyId});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginApplyRowDs(string applyId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("ApplyRowDs", new object[] {
                    applyId}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndApplyRowDs(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void ApplyRowDsAsync(string applyId)
        {
            this.ApplyRowDsAsync(applyId, null);
        }

        /// <remarks/>
        public void ApplyRowDsAsync(string applyId, object userState)
        {
            if ((this.ApplyRowDsOperationCompleted == null))
            {
                this.ApplyRowDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApplyRowDsOperationCompleted);
            }
            this.InvokeAsync("ApplyRowDs", new object[] {
                    applyId}, this.ApplyRowDsOperationCompleted, userState);
        }

        private void OnApplyRowDsOperationCompleted(object arg)
        {
            if ((this.ApplyRowDsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApplyRowDsCompleted(this, new ApplyRowDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void SendGratuityFlowCompletedEventHandler(object sender, SendGratuityFlowCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendGratuityFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SendGratuityFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void ApplyListDsCompletedEventHandler(object sender, ApplyListDsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplyListDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ApplyListDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    public delegate void ApplyRowDsCompletedEventHandler(object sender, ApplyRowDsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApplyRowDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ApplyRowDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}
