//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace winCeshi.HRManager {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HRManagerSoap", Namespace="http://tempuri.org/")]
    public partial class HRManager : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllUserInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByDPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUserInfoByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPostOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDepartmentInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentInfoByUserIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentInfoByDPIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryDepartmentNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryEmployeeNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryPostNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryRankNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryEmployeesByPostIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetManagerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback QueryEmployeesByRankIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HRManager() {
            this.Url = global::winCeshi.Properties.Settings.Default.winCeshi_HRManager_HRManager;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllUserInfoCompletedEventHandler GetAllUserInfoCompleted;
        
        /// <remarks/>
        public event GetUserInfoByDPIDCompletedEventHandler GetUserInfoByDPIDCompleted;
        
        /// <remarks/>
        public event GetUserInfoByUserIDCompletedEventHandler GetUserInfoByUserIDCompleted;
        
        /// <remarks/>
        public event QueryRankCompletedEventHandler QueryRankCompleted;
        
        /// <remarks/>
        public event QueryPostCompletedEventHandler QueryPostCompleted;
        
        /// <remarks/>
        public event GetAllDepartmentInfoCompletedEventHandler GetAllDepartmentInfoCompleted;
        
        /// <remarks/>
        public event GetDepartmentInfoByUserIDCompletedEventHandler GetDepartmentInfoByUserIDCompleted;
        
        /// <remarks/>
        public event GetDepartmentInfoByDPIDCompletedEventHandler GetDepartmentInfoByDPIDCompleted;
        
        /// <remarks/>
        public event QueryDepartmentNameCompletedEventHandler QueryDepartmentNameCompleted;
        
        /// <remarks/>
        public event QueryEmployeeNameCompletedEventHandler QueryEmployeeNameCompleted;
        
        /// <remarks/>
        public event QueryPostNameCompletedEventHandler QueryPostNameCompleted;
        
        /// <remarks/>
        public event QueryRankNameCompletedEventHandler QueryRankNameCompleted;
        
        /// <remarks/>
        public event QueryEmployeesByPostIDCompletedEventHandler QueryEmployeesByPostIDCompleted;
        
        /// <remarks/>
        public event GetManagerInfoCompletedEventHandler GetManagerInfoCompleted;
        
        /// <remarks/>
        public event QueryEmployeesByRankIDCompletedEventHandler QueryEmployeesByRankIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllUserInfo() {
            object[] results = this.Invoke("GetAllUserInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllUserInfoAsync() {
            this.GetAllUserInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllUserInfoAsync(object userState) {
            if ((this.GetAllUserInfoOperationCompleted == null)) {
                this.GetAllUserInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllUserInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllUserInfo", new object[0], this.GetAllUserInfoOperationCompleted, userState);
        }
        
        private void OnGetAllUserInfoOperationCompleted(object arg) {
            if ((this.GetAllUserInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllUserInfoCompleted(this, new GetAllUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoByDPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfoByDPID(string DPID, bool withInherit) {
            object[] results = this.Invoke("GetUserInfoByDPID", new object[] {
                        DPID,
                        withInherit});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByDPIDAsync(string DPID, bool withInherit) {
            this.GetUserInfoByDPIDAsync(DPID, withInherit, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByDPIDAsync(string DPID, bool withInherit, object userState) {
            if ((this.GetUserInfoByDPIDOperationCompleted == null)) {
                this.GetUserInfoByDPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByDPIDOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByDPID", new object[] {
                        DPID,
                        withInherit}, this.GetUserInfoByDPIDOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByDPIDOperationCompleted(object arg) {
            if ((this.GetUserInfoByDPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByDPIDCompleted(this, new GetUserInfoByDPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfoByUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfoByUserID(string userID) {
            object[] results = this.Invoke("GetUserInfoByUserID", new object[] {
                        userID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUserInfoByUserIDAsync(string userID) {
            this.GetUserInfoByUserIDAsync(userID, null);
        }
        
        /// <remarks/>
        public void GetUserInfoByUserIDAsync(string userID, object userState) {
            if ((this.GetUserInfoByUserIDOperationCompleted == null)) {
                this.GetUserInfoByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserInfoByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetUserInfoByUserID", new object[] {
                        userID}, this.GetUserInfoByUserIDOperationCompleted, userState);
        }
        
        private void OnGetUserInfoByUserIDOperationCompleted(object arg) {
            if ((this.GetUserInfoByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUserInfoByUserIDCompleted(this, new GetUserInfoByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryRank", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryRank() {
            object[] results = this.Invoke("QueryRank", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryRankAsync() {
            this.QueryRankAsync(null);
        }
        
        /// <remarks/>
        public void QueryRankAsync(object userState) {
            if ((this.QueryRankOperationCompleted == null)) {
                this.QueryRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryRankOperationCompleted);
            }
            this.InvokeAsync("QueryRank", new object[0], this.QueryRankOperationCompleted, userState);
        }
        
        private void OnQueryRankOperationCompleted(object arg) {
            if ((this.QueryRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryRankCompleted(this, new QueryRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryPost() {
            object[] results = this.Invoke("QueryPost", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPostAsync() {
            this.QueryPostAsync(null);
        }
        
        /// <remarks/>
        public void QueryPostAsync(object userState) {
            if ((this.QueryPostOperationCompleted == null)) {
                this.QueryPostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPostOperationCompleted);
            }
            this.InvokeAsync("QueryPost", new object[0], this.QueryPostOperationCompleted, userState);
        }
        
        private void OnQueryPostOperationCompleted(object arg) {
            if ((this.QueryPostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPostCompleted(this, new QueryPostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllDepartmentInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllDepartmentInfo() {
            object[] results = this.Invoke("GetAllDepartmentInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDepartmentInfoAsync() {
            this.GetAllDepartmentInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetAllDepartmentInfoAsync(object userState) {
            if ((this.GetAllDepartmentInfoOperationCompleted == null)) {
                this.GetAllDepartmentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDepartmentInfoOperationCompleted);
            }
            this.InvokeAsync("GetAllDepartmentInfo", new object[0], this.GetAllDepartmentInfoOperationCompleted, userState);
        }
        
        private void OnGetAllDepartmentInfoOperationCompleted(object arg) {
            if ((this.GetAllDepartmentInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDepartmentInfoCompleted(this, new GetAllDepartmentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentInfoByUserID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDepartmentInfoByUserID(string userID) {
            object[] results = this.Invoke("GetDepartmentInfoByUserID", new object[] {
                        userID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentInfoByUserIDAsync(string userID) {
            this.GetDepartmentInfoByUserIDAsync(userID, null);
        }
        
        /// <remarks/>
        public void GetDepartmentInfoByUserIDAsync(string userID, object userState) {
            if ((this.GetDepartmentInfoByUserIDOperationCompleted == null)) {
                this.GetDepartmentInfoByUserIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentInfoByUserIDOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentInfoByUserID", new object[] {
                        userID}, this.GetDepartmentInfoByUserIDOperationCompleted, userState);
        }
        
        private void OnGetDepartmentInfoByUserIDOperationCompleted(object arg) {
            if ((this.GetDepartmentInfoByUserIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentInfoByUserIDCompleted(this, new GetDepartmentInfoByUserIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepartmentInfoByDPID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDepartmentInfoByDPID(string DPID, bool withInherit) {
            object[] results = this.Invoke("GetDepartmentInfoByDPID", new object[] {
                        DPID,
                        withInherit});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentInfoByDPIDAsync(string DPID, bool withInherit) {
            this.GetDepartmentInfoByDPIDAsync(DPID, withInherit, null);
        }
        
        /// <remarks/>
        public void GetDepartmentInfoByDPIDAsync(string DPID, bool withInherit, object userState) {
            if ((this.GetDepartmentInfoByDPIDOperationCompleted == null)) {
                this.GetDepartmentInfoByDPIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentInfoByDPIDOperationCompleted);
            }
            this.InvokeAsync("GetDepartmentInfoByDPID", new object[] {
                        DPID,
                        withInherit}, this.GetDepartmentInfoByDPIDOperationCompleted, userState);
        }
        
        private void OnGetDepartmentInfoByDPIDOperationCompleted(object arg) {
            if ((this.GetDepartmentInfoByDPIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentInfoByDPIDCompleted(this, new GetDepartmentInfoByDPIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryDepartmentName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryDepartmentName(string departmentID) {
            object[] results = this.Invoke("QueryDepartmentName", new object[] {
                        departmentID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryDepartmentNameAsync(string departmentID) {
            this.QueryDepartmentNameAsync(departmentID, null);
        }
        
        /// <remarks/>
        public void QueryDepartmentNameAsync(string departmentID, object userState) {
            if ((this.QueryDepartmentNameOperationCompleted == null)) {
                this.QueryDepartmentNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryDepartmentNameOperationCompleted);
            }
            this.InvokeAsync("QueryDepartmentName", new object[] {
                        departmentID}, this.QueryDepartmentNameOperationCompleted, userState);
        }
        
        private void OnQueryDepartmentNameOperationCompleted(object arg) {
            if ((this.QueryDepartmentNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryDepartmentNameCompleted(this, new QueryDepartmentNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryEmployeeName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryEmployeeName(string employeeID) {
            object[] results = this.Invoke("QueryEmployeeName", new object[] {
                        employeeID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryEmployeeNameAsync(string employeeID) {
            this.QueryEmployeeNameAsync(employeeID, null);
        }
        
        /// <remarks/>
        public void QueryEmployeeNameAsync(string employeeID, object userState) {
            if ((this.QueryEmployeeNameOperationCompleted == null)) {
                this.QueryEmployeeNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryEmployeeNameOperationCompleted);
            }
            this.InvokeAsync("QueryEmployeeName", new object[] {
                        employeeID}, this.QueryEmployeeNameOperationCompleted, userState);
        }
        
        private void OnQueryEmployeeNameOperationCompleted(object arg) {
            if ((this.QueryEmployeeNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryEmployeeNameCompleted(this, new QueryEmployeeNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryPostName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryPostName(string postID) {
            object[] results = this.Invoke("QueryPostName", new object[] {
                        postID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryPostNameAsync(string postID) {
            this.QueryPostNameAsync(postID, null);
        }
        
        /// <remarks/>
        public void QueryPostNameAsync(string postID, object userState) {
            if ((this.QueryPostNameOperationCompleted == null)) {
                this.QueryPostNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPostNameOperationCompleted);
            }
            this.InvokeAsync("QueryPostName", new object[] {
                        postID}, this.QueryPostNameOperationCompleted, userState);
        }
        
        private void OnQueryPostNameOperationCompleted(object arg) {
            if ((this.QueryPostNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPostNameCompleted(this, new QueryPostNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryRankName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryRankName(string rankID) {
            object[] results = this.Invoke("QueryRankName", new object[] {
                        rankID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryRankNameAsync(string rankID) {
            this.QueryRankNameAsync(rankID, null);
        }
        
        /// <remarks/>
        public void QueryRankNameAsync(string rankID, object userState) {
            if ((this.QueryRankNameOperationCompleted == null)) {
                this.QueryRankNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryRankNameOperationCompleted);
            }
            this.InvokeAsync("QueryRankName", new object[] {
                        rankID}, this.QueryRankNameOperationCompleted, userState);
        }
        
        private void OnQueryRankNameOperationCompleted(object arg) {
            if ((this.QueryRankNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryRankNameCompleted(this, new QueryRankNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryEmployeesByPostID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryEmployeesByPostID(string postID, bool includeChild) {
            object[] results = this.Invoke("QueryEmployeesByPostID", new object[] {
                        postID,
                        includeChild});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryEmployeesByPostIDAsync(string postID, bool includeChild) {
            this.QueryEmployeesByPostIDAsync(postID, includeChild, null);
        }
        
        /// <remarks/>
        public void QueryEmployeesByPostIDAsync(string postID, bool includeChild, object userState) {
            if ((this.QueryEmployeesByPostIDOperationCompleted == null)) {
                this.QueryEmployeesByPostIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryEmployeesByPostIDOperationCompleted);
            }
            this.InvokeAsync("QueryEmployeesByPostID", new object[] {
                        postID,
                        includeChild}, this.QueryEmployeesByPostIDOperationCompleted, userState);
        }
        
        private void OnQueryEmployeesByPostIDOperationCompleted(object arg) {
            if ((this.QueryEmployeesByPostIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryEmployeesByPostIDCompleted(this, new QueryEmployeesByPostIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetManagerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetManagerInfo() {
            object[] results = this.Invoke("GetManagerInfo", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetManagerInfoAsync() {
            this.GetManagerInfoAsync(null);
        }
        
        /// <remarks/>
        public void GetManagerInfoAsync(object userState) {
            if ((this.GetManagerInfoOperationCompleted == null)) {
                this.GetManagerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetManagerInfoOperationCompleted);
            }
            this.InvokeAsync("GetManagerInfo", new object[0], this.GetManagerInfoOperationCompleted, userState);
        }
        
        private void OnGetManagerInfoOperationCompleted(object arg) {
            if ((this.GetManagerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetManagerInfoCompleted(this, new GetManagerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryEmployeesByRankID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet QueryEmployeesByRankID(string rankID, bool includeChild) {
            object[] results = this.Invoke("QueryEmployeesByRankID", new object[] {
                        rankID,
                        includeChild});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void QueryEmployeesByRankIDAsync(string rankID, bool includeChild) {
            this.QueryEmployeesByRankIDAsync(rankID, includeChild, null);
        }
        
        /// <remarks/>
        public void QueryEmployeesByRankIDAsync(string rankID, bool includeChild, object userState) {
            if ((this.QueryEmployeesByRankIDOperationCompleted == null)) {
                this.QueryEmployeesByRankIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryEmployeesByRankIDOperationCompleted);
            }
            this.InvokeAsync("QueryEmployeesByRankID", new object[] {
                        rankID,
                        includeChild}, this.QueryEmployeesByRankIDOperationCompleted, userState);
        }
        
        private void OnQueryEmployeesByRankIDOperationCompleted(object arg) {
            if ((this.QueryEmployeesByRankIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryEmployeesByRankIDCompleted(this, new QueryEmployeesByRankIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllUserInfoCompletedEventHandler(object sender, GetAllUserInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetUserInfoByDPIDCompletedEventHandler(object sender, GetUserInfoByDPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByDPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByDPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetUserInfoByUserIDCompletedEventHandler(object sender, GetUserInfoByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUserInfoByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUserInfoByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryRankCompletedEventHandler(object sender, QueryRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryPostCompletedEventHandler(object sender, QueryPostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetAllDepartmentInfoCompletedEventHandler(object sender, GetAllDepartmentInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDepartmentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDepartmentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDepartmentInfoByUserIDCompletedEventHandler(object sender, GetDepartmentInfoByUserIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentInfoByUserIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentInfoByUserIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetDepartmentInfoByDPIDCompletedEventHandler(object sender, GetDepartmentInfoByDPIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentInfoByDPIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentInfoByDPIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryDepartmentNameCompletedEventHandler(object sender, QueryDepartmentNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryDepartmentNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryDepartmentNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryEmployeeNameCompletedEventHandler(object sender, QueryEmployeeNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryEmployeeNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryEmployeeNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryPostNameCompletedEventHandler(object sender, QueryPostNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPostNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryPostNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryRankNameCompletedEventHandler(object sender, QueryRankNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryRankNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryRankNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryEmployeesByPostIDCompletedEventHandler(object sender, QueryEmployeesByPostIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryEmployeesByPostIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryEmployeesByPostIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetManagerInfoCompletedEventHandler(object sender, GetManagerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetManagerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetManagerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void QueryEmployeesByRankIDCompletedEventHandler(object sender, QueryEmployeesByRankIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryEmployeesByRankIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QueryEmployeesByRankIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591